---
- name: Install .env config
  template:
    src: .env.j2
    dest: "{{ bridge_path }}/monitor/.env"
  when: skip_task != true

- name: Copy bridge config files names
  copy:
    src: ../../../../monitor/configs/
    dest: "{{ bridge_path }}/monitor/configs"
